// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAssetByCode = `-- name: GetAssetByCode :one
SELECT id, code, name, created_at
FROM assets
WHERE code = $1
`

func (q *Queries) GetAssetByCode(ctx context.Context, code string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByCode, code)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetById = `-- name: GetAssetById :one
SELECT id, code, name, created_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetById(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetById, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
