// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (amount, transaction_id, wallet_id)
VALUES ($1, $2, $3)
RETURNING id, amount, transaction_id, wallet_id, created_at
`

type CreateLedgerParams struct {
	Amount        int32     `json:"amount"`
	TransactionID uuid.UUID `json:"transaction_id"`
	WalletID      uuid.UUID `json:"wallet_id"`
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, createLedger, arg.Amount, arg.TransactionID, arg.WalletID)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TransactionID,
		&i.WalletID,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(amount), 0)
FROM ledgers
WHERE wallet_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, walletID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getBalance, walletID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getLedgerById = `-- name: GetLedgerById :one
SELECT id, amount, transaction_id, wallet_id, created_at
FROM ledgers
WHERE id = $1
`

func (q *Queries) GetLedgerById(ctx context.Context, id uuid.UUID) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedgerById, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TransactionID,
		&i.WalletID,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerByWalletAndTnx = `-- name: GetLedgerByWalletAndTnx :one
SELECT id, amount, transaction_id, wallet_id, created_at
FROM ledgers
WHERE wallet_id = $1 AND transaction_id = $2
`

type GetLedgerByWalletAndTnxParams struct {
	WalletID      uuid.UUID `json:"wallet_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
}

func (q *Queries) GetLedgerByWalletAndTnx(ctx context.Context, arg GetLedgerByWalletAndTnxParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedgerByWalletAndTnx, arg.WalletID, arg.TransactionID)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TransactionID,
		&i.WalletID,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgersByWalletId = `-- name: GetLedgersByWalletId :many
SELECT id, amount, transaction_id, wallet_id, created_at
FROM ledgers
WHERE wallet_id = $1
ORDER BY
  CASE WHEN $4 = 'asc'  THEN created_at END ASC,
  CASE WHEN $4 = 'desc' THEN created_at END DESC,
  created_at DESC
LIMIT COALESCE($2, 5)
OFFSET COALESCE($3, 0)
`

type GetLedgersByWalletIdParams struct {
	WalletID uuid.UUID   `json:"wallet_id"`
	Column2  interface{} `json:"column_2"`
	Column3  interface{} `json:"column_3"`
	Column4  interface{} `json:"column_4"`
}

func (q *Queries) GetLedgersByWalletId(ctx context.Context, arg GetLedgersByWalletIdParams) ([]Ledger, error) {
	rows, err := q.db.Query(ctx, getLedgersByWalletId,
		arg.WalletID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TransactionID,
			&i.WalletID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
