// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionType string

const (
	TransactionTypeSPEND TransactionType = "SPEND"
	TransactionTypeTOPUP TransactionType = "TOPUP"
	TransactionTypeBONUS TransactionType = "BONUS"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type WalletOwnerType string

const (
	WalletOwnerTypeUSER   WalletOwnerType = "USER"
	WalletOwnerTypeSYSTEM WalletOwnerType = "SYSTEM"
)

func (e *WalletOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletOwnerType(s)
	case string:
		*e = WalletOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletOwnerType: %T", src)
	}
	return nil
}

type NullWalletOwnerType struct {
	WalletOwnerType WalletOwnerType `json:"wallet_owner_type"`
	Valid           bool            `json:"valid"` // Valid is true if WalletOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletOwnerType), nil
}

type Asset struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Ledger struct {
	ID            uuid.UUID          `json:"id"`
	Amount        int32              `json:"amount"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	WalletID      uuid.UUID          `json:"wallet_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID        uuid.UUID          `json:"id"`
	Type      TransactionType    `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID        uuid.UUID          `json:"id"`
	OwnerType WalletOwnerType    `json:"owner_type"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	AssetID   uuid.UUID          `json:"asset_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
