// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error)
	CreateTxn(ctx context.Context, arg CreateTxnParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	GetAssetByCode(ctx context.Context, code string) (Asset, error)
	GetAssetById(ctx context.Context, id uuid.UUID) (Asset, error)
	GetBalance(ctx context.Context, walletID uuid.UUID) (interface{}, error)
	GetLedgerById(ctx context.Context, id uuid.UUID) (Ledger, error)
	GetLedgerByWalletAndTnx(ctx context.Context, arg GetLedgerByWalletAndTnxParams) (Ledger, error)
	GetLedgersByWalletId(ctx context.Context, arg GetLedgersByWalletIdParams) ([]Ledger, error)
	GetSystemWallet(ctx context.Context) (uuid.UUID, error)
	GetTransactionById(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionByType(ctx context.Context, arg GetTransactionByTypeParams) ([]Transaction, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWalletById(ctx context.Context, id uuid.UUID) (Wallet, error)
	GetWalletByOwner(ctx context.Context, ownerID uuid.UUID) (Wallet, error)
	LockWallet(ctx context.Context, ownerID uuid.UUID) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
