// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTxn = `-- name: CreateTxn :one
INSERT INTO transactions (id, type)
VALUES ($1, $2)
RETURNING id, type, created_at
`

type CreateTxnParams struct {
	ID   uuid.UUID       `json:"id"`
	Type TransactionType `json:"type"`
}

func (q *Queries) CreateTxn(ctx context.Context, arg CreateTxnParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTxn, arg.ID, arg.Type)
	var i Transaction
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, type, created_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionById(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getTransactionByType = `-- name: GetTransactionByType :many
SELECT id, type, created_at
FROM transactions
WHERE type = $1
ORDER BY
  CASE WHEN $4 = 'asc' THEN created_at END ASC,
  CASE WHEN $4 = 'desc' THEN created_at END DESC,
  created_at DESC
LIMIT COALESCE($2, 5)
OFFSET COALESCE($3, 0)
`

type GetTransactionByTypeParams struct {
	Type    TransactionType `json:"type"`
	Column2 interface{}     `json:"column_2"`
	Column3 interface{}     `json:"column_3"`
	Column4 interface{}     `json:"column_4"`
}

func (q *Queries) GetTransactionByType(ctx context.Context, arg GetTransactionByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByType,
		arg.Type,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
