// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (owner_type, owner_id, asset_id)
VALUES ($1, $2, $3)
RETURNING id, owner_type, owner_id, asset_id, created_at
`

type CreateWalletParams struct {
	OwnerType WalletOwnerType `json:"owner_type"`
	OwnerID   uuid.UUID       `json:"owner_id"`
	AssetID   uuid.UUID       `json:"asset_id"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.OwnerType, arg.OwnerID, arg.AssetID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.AssetID,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemWallet = `-- name: GetSystemWallet :one
SELECT id
FROM wallets
WHERE owner_type = 'SYSTEM'
`

func (q *Queries) GetSystemWallet(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSystemWallet)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWalletById = `-- name: GetWalletById :one
SELECT id, owner_type, owner_id, asset_id, created_at
FROM wallets
WHERE id = $1
`

func (q *Queries) GetWalletById(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletById, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.AssetID,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByOwner = `-- name: GetWalletByOwner :one
SELECT id, owner_type, owner_id, asset_id, created_at
FROM wallets
WHERE owner_id = $1
`

func (q *Queries) GetWalletByOwner(ctx context.Context, ownerID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByOwner, ownerID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.AssetID,
		&i.CreatedAt,
	)
	return i, err
}

const lockWallet = `-- name: LockWallet :one
SELECT id
FROM wallets
WHERE owner_id = $1
FOR UPDATE
`

func (q *Queries) LockWallet(ctx context.Context, ownerID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockWallet, ownerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
